server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.29.2.156:3306/elog?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  path: logs
  level:
    com.study: info
  file:
    max-size: 100MB